### ISSUE TITLE
Upgrading chilipie

### ISSUE THREAD

**Issue by kovacicjanez** [futurice/chilipie-kiosk#166]
Hi.

Is it possible to upgrade chilipie form 2.1.0 to newer version 3.0.0?
I don't wont to reconfigure everything from the start.

or is thare any option to use 2.1.0 image made from raspberry pi 3 on raspberry 4?

**Comment by jareware** [comment]
Unfortunately there's no "upgrade" path between images, since they are by definition complete snapshots of the SD card.

However, the image hasn't changed that dramatically since, so if your configuration is done to Chromium for instance, you should be able to just zip up its profile from your current image, and put it into place on the new image.

Best of luck!
