### ISSUE TITLE
Wifi with username/password

### ISSUE THREAD

**Issue by steigenTI** [futurice/chilipie-kiosk#32]
Having a hard time finding docs on turning on wifi for more complex networks that require an ssid, username, and password. Is this feature supported at all?

**Comment by jareware** [comment]
Yes it is, at least as far as it's supported by the `raspi-config` utility!

Check out [these docs](https://github.com/futurice/chilipie-kiosk/blob/master/docs/first-boot.md#system-configuration) for how to access it.

**Comment by albatrossLol** [comment]
Running on approved hardware, I get an error with Raspi-Config

"cannot communicate with wpa_supplicant"

wifi country, SSID, password, etc are all correct. the hardwire lan connection works, but the unit will need to be deployed in a wireless environment.

I've tried reflashing the SD card with fresh installs, but still get the same error. The hardware is known good in other distros.

**Comment by jareware** [comment]
@albatrossLol curious! Which hardware are you using? Have you tried flashing vanilla Raspbian? Can you join the WiFi with that?

**Comment by albatrossLol** [comment]
> @albatrossLol curious! Which hardware are you using? Have you tried flashing vanilla Raspbian? Can you join the WiFi with that?

Ok - so I decided to go all the way back down to the basics and do some additional parity testing. Turns out that the somewhere in between the install and implementationm, the wifi chip went bad on 1 of the Rpi 3b's (not +). It joined with eth0 but wlan0 would not show up.

Swapped boards out, reinstalled all and took it from the bench to production room. At first I thought it was hosed again - but I believe I got the connection reset this final time because it was trying to connect to eth0 first this time -- waited a bit and came back and it had switched over to wireless. woo! I'm up and running with no issues. Once it latched onto wireless it took it and ran. We LOVE this and allows us to run Dakboard as a command station for the family.

I had also tested on the Rpi 0 W and it worked very with the exception of rebooting nightly -- it would boot back into the raspi-config page each time until I manually rebooted. I know that piece of hardware wasn't on the list, but wanted to try it anyway.

**Comment by jareware** [comment]
Oh, just bad luck it seems. Glad you got it working!

Had to look up DAKboard, looks really nice.

A person at my work has actually also set up a 0W-based kiosk and I think at least their initial experiences were positive. If it ends up working for them let's see if we can make the 0W also officially supported!

Anyway, this issue seems sorted out, I'll go ahead and close.
